# Generated by Django 6.1 on 2026-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
